
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;

public class Master {

	public static void main(String[] args) throws FileNotFoundException {
		int wordsPerSentence = 10;
		Dictionary.instantiate();
		ArrayList<String> dict = Dictionary.getDict();
		RandomSentenceGeneratorFromDictionary rwDict = new RandomSentenceGeneratorFromDictionary(dict);
		RandomWordGeneratorFromLetters rw = new RandomWordGeneratorFromLetters();
		System.out.println("Sentence generated using Random letters: "+ rw.generateSentence(4, wordsPerSentence));
		System.out.println("Sentence generated using Random words from dictionary: " + rwDict.generateSentence());
		String sentence = "";
		while (wordsPerSentence > 0) {
			sentence += rwDict.getNextWord("the") + " ";
			wordsPerSentence--;
		}
		System.out.println("Sentence generated by markov principle: " + sentence);
	}
}
